defmodule Demo.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    alter table(:users) do
      modify(:id, :binary_id, default: fragment("uuid_generate_v4()"))
    end

    drop(constraint(:tickets, "tickets_representative_id_fkey"))

    alter table(:tickets) do
      modify(:id, :binary_id, default: fragment("uuid_generate_v4()"))
      modify(:representative_id, references("users", type: :binary_id, column: :id))
    end
  end

  def down() do
    drop(constraint(:tickets, "tickets_representative_id_fkey"))

    alter table(:tickets) do
      modify(:representative_id, references("users", type: :binary_id, column: :id))
      modify(:id, :binary_id, default: nil)
    end

    alter table(:users) do
      modify(:id, :binary_id, default: nil)
    end
  end
end