# SPDX-FileCopyrightText: 2020 Zach Daniel
# SPDX-FileCopyrightText: 2020 ash_admin contributors <https://github.com/ash-project/ash_admin/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule Demo.Repo.Migrations.AddPrivateAndSensitiveFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :api_key, :text
      add :date_of_birth, :date
    end
  end

  def down do
    alter table(:users) do
      remove :date_of_birth
      remove :api_key
    end
  end
end
