defmodule Demo.Repo.Migrations.AddPhotoPaths do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:photo_path, :text)
    end

    alter table(:tickets) do
      add(:photo_path, :text)
    end
  end

  def down do
    alter table(:tickets) do
      remove(:photo_path)
    end

    alter table(:users) do
      remove(:photo_path)
    end
  end
end
