defmodule Demo.Repo.Migrations.AddOfficesAndMemberships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:offices, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:location, :text)
    end

    create table(:memberships, primary_key: false) do
      add(
        :user_id,
        references(:users,
          column: :id,
          name: "memberships_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)

      add(
        :office_id,
        references(:offices,
          column: :id,
          name: "memberships_office_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)
    end
  end

  def down do
    drop(constraint(:memberships, "memberships_user_id_fkey"))

    drop(constraint(:memberships, "memberships_office_id_fkey"))

    drop(table(:memberships))

    drop(table(:offices))
  end
end
