defmodule Demo.Repo.Migrations.AddOfficeLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:office_links, primary_key: false) do
      add(:relationship_type, :text, null: false, default: "partner")

      add(
        :source_office_id,
        references(:offices,
          column: :id,
          name: "office_links_source_office_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)

      add(
        :destination_office_id,
        references(:offices,
          column: :id,
          name: "office_links_destination_office_id_fkey",
          type: :uuid,
          prefix: "public"
        ), primary_key: true, null: false)
    end
  end

  def down do
    drop(constraint(:office_links, "office_links_source_office_id_fkey"))

    drop(constraint(:office_links, "office_links_destination_office_id_fkey"))

    drop(table(:office_links))
  end
end
