defmodule Demo.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :bio, :map
      add :alternate_bios, {:array, :map}
    end
  end

  def down do
    alter table(:users) do
      remove :alternate_bios
      remove :bio
    end
  end
end