defmodule Demo.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ticket_links) do
      modify :type, :text, null: false
    end
  end

  def down do
    alter table(:ticket_links) do
      modify :type, :text, null: true
    end
  end
end