defmodule Demo.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_links, primary_key: false) do
      add :source_id, references(:tickets, type: :uuid, column: :id), primary_key: true
      add :destination_id, references(:tickets, type: :uuid, column: :id), primary_key: true
    end
  end

  def down do
    drop table(:ticket_links)
  end
end