defmodule Demo.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :alternate_bios, to: :alternate_profiles

    rename table(:users), :bio, to: :profile
  end

  def down do
    rename table(:users), :profile, to: :bio

    rename table(:users), :alternate_profiles, to: :alternate_bios
  end
end
